# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Datama Documentation
email: contact@Datama.fr
description: >- # this means to ignore newlines until "baseurl:"
  Welcome on Datama Documentation
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://Datama-solutions.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Sass options
sass:
  quiet_deps: true

# Default permalinks: year/month/day/title.html
permalink: /:categories/:year/:month/:day/:title:output_ext

include:
  - .well-known

collections:
  posts:
    output: true
    # EN by default (tips_of_the_week)
    permalink: /en/:year/:month/:day/:title:output_ext

# Folder-specific permalink rules to avoid EN/FR collisions
defaults:
  - scope:
      path: "_posts/tips_of_the_week_fr"
      type: "posts"
    values:
      permalink: /fr/:year/:month/:day/:title:output_ext
  - scope:
      path: "_posts/tips_of_the_week"
      type: "posts"
    values:
      permalink: /en/:year/:month/:day/:title:output_ext

feed:
  path: feed_totw_en.xml
  output: true
  title: Tip of the week FR
  description: Le nouveau conseil de la semaine
  url: /docs/tips/fr
  tip_of_the_week_fr:
    path: feed_totw_fr.xml
    output: true
    title: Tip of the week FR
    description: Le nouveau conseil de la semaine
    url: /docs/tips/fr

  tip_of_the_week_en:
    path: feed_totw_en.xml
    output: true
    title: Tip of the week
    description: The latest tip of the week
    url: /docs/tips/en
# French feed still under /docs/tips/fr
#  - jekyll-sitemap

    exclude:
      - .well-known/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
